// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKLGPmAALPd4gWd3dWTMRHAZxObgWoxU',
    appId: '1:345351434908:web:243758a2f1a2c8818df359',
    messagingSenderId: '345351434908',
    projectId: 'calcswift-nbkg2',
    authDomain: 'calcswift-nbkg2.firebaseapp.com',
    storageBucket: 'calcswift-nbkg2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtAXJJFlNzAeOqsjeNfKW3KJDwJDkvMBI',
    appId: '1:345351434908:android:c1b1788c769b2e3c8df359',
    messagingSenderId: '345351434908',
    projectId: 'calcswift-nbkg2',
    storageBucket: 'calcswift-nbkg2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlL-wQq-_1LElN0uk06YywjA5HQQdf3A',
    appId: '1:345351434908:ios:955debcbe5e841908df359',
    messagingSenderId: '345351434908',
    projectId: 'calcswift-nbkg2',
    storageBucket: 'calcswift-nbkg2.firebasestorage.app',
    iosBundleId: 'mn.erdenee.halloween',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlL-wQq-_1LElN0uk06YywjA5HQQdf3A',
    appId: '1:345351434908:ios:141f6df1f212840a8df359',
    messagingSenderId: '345351434908',
    projectId: 'calcswift-nbkg2',
    storageBucket: 'calcswift-nbkg2.firebasestorage.app',
    iosBundleId: 'com.example.halloween',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFKLGPmAALPd4gWd3dWTMRHAZxObgWoxU',
    appId: '1:345351434908:web:8764b30b834a12278df359',
    messagingSenderId: '345351434908',
    projectId: 'calcswift-nbkg2',
    authDomain: 'calcswift-nbkg2.firebaseapp.com',
    storageBucket: 'calcswift-nbkg2.firebasestorage.app',
  );
}
